### ISSUE TITLE
Quit a legend after adding it

### ISSUE THREAD

**Issue by enriquevaa** [walkerke/mapgl#10]
I have developed a shiny app where I can switch from different layers, for example, heatmap, population, and locations.
I use the function clear_layer() to quit the polygons when I switch from one layer to another; however, there's no function to remove the legend added through add_legend(), even if I add an option in the shiny app to render the map again the legend is still there. 

Is there a way to remove the legend? Thanks!

**Comment by walkerke** [comment]
Yes, a `clear_legend()` function would make a lot of sense!  I'll take a look at it.

**Comment by walkerke** [comment]
`clear_legend()` is now implement, and works with your app!
