### ISSUE TITLE
Use empty/solid color basemap

### ISSUE THREAD

**Issue by CIOData** [walkerke/mapgl#28]
I am trying to create a map using shifted geometry for the US (i.e. Alaska and Hawaii moved), and need to have an empty/solid color basemap option for displaying it. I can't seem to find an option for doing this in `mapboxgl()` or `maplibre()`.

**Comment by walkerke** [comment]
It's kind of a wonky solution, based on this: https://gis.stackexchange.com/questions/398348/mapbox-map-with-no-style-only-self-hosted-vector-data

I'd be open to it as a feature request!  Note that the Albers projection is only available in Mapbox, not MapLibre.  

```r
library(mapgl)
library(tigris)
library(jsonlite)

js_object <- list(
  version = 8,
  sources = structure(list(), .Names = character(0)),
  layers = list()
)

json_output <- toJSON(js_object, auto_unbox = TRUE, pretty = TRUE)

us_states <- states(cb = TRUE, resolution = "20m") |> 
  shift_geometry()

mapboxgl(style = json_output,
         projection = "albers",
         center = c(-98.8, 37.68),
         zoom = 3.4) |>
  add_fill_layer(
    id = "states",
    source = us_states,
    fill_color = "navy",
    fill_opacity = 0.7,
    tooltip = "NAME"
  )
```

![image](https://github.com/user-attachments/assets/b53d3b83-040c-4498-b135-45bc929d724f)

**Comment by walkerke** [comment]
You can also author a custom blank style with a background in Mapbox Studio, then use that.  Here I've got a style with a light grey background I set up in Studio. 

```r
style_url <- "mapbox://styles/kwalkertcu/clz2wwap502f301pafh8ad1zv/draft"

mapboxgl(style = style_url,
         projection = "albers",
         center = c(-98.8, 37.68),
         zoom = 3.4) |>
  add_fill_layer(
    id = "states",
    source = us_states,
    fill_color = "navy",
    fill_opacity = 0.7,
    tooltip = "NAME"
  )
```

![image](https://github.com/user-attachments/assets/d247f4a5-b694-4a7f-b6b3-1f732549180f)

**Comment by CIOData** [comment]
This was helpful, but I've run into a funny issue. When I try to use this solution with `add_fill_extrusion()` I get a half copy of the map off in the distance at certain zoom levels.

![image](https://github.com/user-attachments/assets/961291d1-f811-43c4-9aa4-be720767e0a7)

This does not happen when I use just `add_fill_layer()`. 

![image](https://github.com/user-attachments/assets/7bddd5a5-dc13-4188-9ecb-f0a43070e517)

Any thoughts on what might be happening? I can't seem to figure it out.
