### ISSUE TITLE
styling for draw controls

### ISSUE THREAD

**Issue by ews-grmunjal** [walkerke/mapgl#33]
Hi Kyle, would it be possible to allow passing custom css for the draw control? or could you make an example (as your time allows) on how to do this?

I am able to change most things about the styling using just mapgl controls and passing new styles to them (see example below) but not able to change the layout and positioning....what i want is the toolbar horizontal and bottom-center. 

Also, currently for me the default top_left works great but it goes under legends I may have on top_left.... all other positions seem to send the draw_control out of the map

![image](https://github.com/user-attachments/assets/f560ffc0-4245-44b8-b652-153f1b824fcd)

**Comment by walkerke** [comment]
I don't know how to do that just yet - your styling looks really cool!  I'm not seeing the same issue as you with the draw control being rendered out of the map.

**Comment by walkerke** [comment]
This is now possible thanks to the updates in Mapbox GL JS 3.7.0!

```r
mapboxgl() |> add_draw_control(orientation = "horizontal", position = "bottom")
```

![image](https://github.com/user-attachments/assets/61051bcb-bf56-4f4d-b631-d317962eb604)
