### ISSUE TITLE
No option to fit title length in add_legend() for continuous values

### ISSUE THREAD

**Issue by CIOData** [walkerke/mapgl#40]
I am adding legends to fill layers in mapgl, but can't find a way to get the box to auto fit the width of the title when using continuous values. Legends for categorical values seem to do this by default. Ideally, the width will be auto by default for continuous legends as well so that it can accommodate dynamic titles in a Shiny app.

Continuous:
![image](https://github.com/user-attachments/assets/fc6da2c4-60d9-41f8-b08e-ecb0ce946b10)

Categorical:
![image](https://github.com/user-attachments/assets/5368fad2-676a-4f4f-8993-507aec91f89e)

**Comment by walkerke** [comment]
I'll take a look at that.  Something I never liked about how Leaflet handled legends is that they allowed this behavior, creating really wide legends that would overlap too much onto the data unless you use `<br>` tags.  

However, it would be straightforward to expose a `max_width` parameter for legends, allowing you to enable this.

**Comment by CIOData** [comment]
Thanks. That would be helpful for maps generated in RStudio. I was able to fix it myself when used in a Shiny app by adjusting the CSS to width: auto; and max-width: auto;.

I'm not a fan of the leaflet legends either, but have enjoyed the outputs from leaflegend.
________________________________
