### ISSUE TITLE
blank Viewer in RStudio

### ISSUE THREAD

**Issue by wiesehahn** [walkerke/mapgl#43]
When using the package functions to create an interactive map with e.g. something like the following from RStudio
```r
library(mapgl)
maplibre()
```
the Viewer pane keeps blank. This is probably no mapgl issue, but is it expected?

When exporting/saving as a webpage the map is visible as expected in the browser.

**Comment by walkerke** [comment]
I've seen that once before, but only for Mapbox maps, and it resolved itself and hasn't happened again.  What version of RStudio are you running?

**Comment by wiesehahn** [comment]
I used a version from april, so I just updated RStudio to the newest version but the problem persists. Still when opening in a new (browser) window no problem.

**Comment by wiesehahn** [comment]
the html we generate includes e.g. 
```
  // See if we're running in a viewer pane. If not, we're in a web browser.
  var viewerMode = window.HTMLWidgets.viewerMode =
      /\bviewer_pane=1\b/.test(window.location);
```
probably this is somehow related?!

**Comment by walkerke** [comment]
I'll look into that - however I can't reproduce the issue on my end, it shows up fine in the viewer.  What is your operating system?
