### ISSUE TITLE
Add Source issue for set terrain

### ISSUE THREAD

**Issue by sailbot24** [walkerke/mapgl#47]
the example provided in the set terrain documentaion - 

map <- mapboxgl(style = "mapbox://styles/mapbox/satellite-streets-v12",
                center = c(-111.658106, 40.582623), 
                zoom = 10, 
                pitch = 45, 
                bearing = 180)

map <- add_source(map, id = "mapbox-dem", type = "raster-dem",
                  url = "mapbox://mapbox.mapbox-terrain-dem-v1",
                  tileSize = 512, maxzoom = 14)

map <- set_terrain(map, source = "mapbox-dem", exaggeration = 1.5)

leads to this error - 
Error in add_source(map, id = "mapbox-dem", type = "raster-dem", url = "mapbox://mapbox.mapbox-terrain-dem-v1",  : 
  argument "data" is missing, with no default

**Comment by walkerke** [comment]
Thanks for the catch!  I've updated the docs.  Try out the updated example:

```r
library(mapgl)

mapboxgl(
  style = mapbox_style("standard-satellite"),
  center = c(-114.26608, 32.7213),
  zoom = 14,
  pitch = 80,
  bearing = 41
) |> 
  add_raster_dem_source(
    id = "mapbox-dem",
    url = "mapbox://mapbox.mapbox-terrain-dem-v1",
    tileSize = 512, 
    maxzoom = 14
  ) |> 
  set_terrain(
    source = "mapbox-dem", 
    exaggeration = 1.5
  )
```
